swipe:
  3:
    left:
      command: "xdotool key ctrl+alt+Right"
    right:
      command: "xdotool key ctrl+alt+Left"
    up:
      command: "xdotool key super+g"
    down:
      command: "xdotool key Escape"
  4:
    right:
      command: "playerctl previous"
    left:
      command: "playerctl next"
    up:
      command: "amixer -q set Master 5%+"
      threshold: 0.2
      interval: 0.2
    down:
      command: "amixer -q set Master 5%-"
      threshold: 0.2
      interval: 0.2
hold:
  4:
    command: "playerctl play-pause"

pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
    out:
      command: 'xdotool key ctrl+minus'
  3:
    in:
      command: 'xdotool key super+f'
    out:
      command: 'xdotool key super+f'

threshold:
  swipe: 1
  pinch: 0.2

interval:
  swipe: 1
  pinch: 0.2

plugin: 
  inputs:
    libinput_command_input:
      enable-tap: true
      verbose: true