# export STARSHIP_CONFIG=.config/starship/starship.toml #todo add permanentlty


# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true


[git_branch]
always_show_remote = false
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "bold yellow"


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true